language: python
install:
  - pip install tox
python: 3.5
script:
  - tox -e $TOX_ENV

matrix:
  inlcude:
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
